# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-26 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkscore',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.Homework', verbose_name='作业'),
        ),
    ]
